### ISSUE TITLE
add link tags around div

### ISSUE THREAD

**Issue by tommiecc** [a456pur/seraph#12]
**suggestion**
at the moment you have to click on the text to go to the game. change this so that you can click on the image as well to go to the game.

_Before_
```
<div ...>
    <a href="....">
        ...
    </a>
</div>
```

_After_
```
<a href="...">
    <div ...>
        ...
    </div>
</a>
```

**Comment by a456pur** [comment]
THERE'S NO WAY I SEE THIS AFTER PUBLISHING V4
will do for v5

**Comment by a456pur** [comment]
done for v5 :)
