### ISSUE TITLE
very tiny bug that doesnt affect anyone but funny

### ISSUE THREAD

**Issue by skysthelimitt** [a456pur/seraph#13]
**what is the bug**
you can just make the screen scroll away

**reproduce**
while holding left click down, just move your mouse to the right, as soon as ur mouse hits the edge, the screen scrolls away

**additional notes**
probably bc of the custom cursor, also having inspect element open on the right makes it scroll even faster

**Comment by a456pur** [comment]
aware of the bug (you don't even need to hold left click lol) and should be fixed in v5.1 releasing later today
thank you for the report

**Comment by a456pur** [comment]
issue fixed with v5.1, now out now
