### ISSUE TITLE
use an official ruffle cdn instead of selfhosting

### ISSUE THREAD

**Issue by skysthelimitt** [a456pur/seraph#14]
another minor thing, but id recommend using the official ruffle cdn they have listed on their website, just bc you can get the latest version of ruffle with support for more flash games and it could lower bandwidth costs (assuming someone hosts it on their own server or smth)
once again a very minor thing, but could be very useful later on

**Comment by a456pur** [comment]
might put this in for next update (?)
also considering keeping the selfhost so if the ruffle cdn fails for whatever reason or a user is offline the website can fallback to the localhost

**Comment by skysthelimitt** [comment]
ive never had any issues using the unpkg link provided by ruffle in my experience at least

**Comment by a456pur** [comment]
unpkg seems really reliable yeah, just making sure website has a fallback plan
probably will do this for emulatorjs as well

**Comment by a456pur** [comment]
update on this: i've implemented a solution for this in preparation for v6 (release tmrw)

there's now a new script implemented into pages that use ruffle that uses the cdn and prefers to use it, however if unpkg is down or more likely a user is using a downloaded copy of the website without internet the page will use the local copy of ruffle stored on the website, hopefully reducing bandwidth !

i'll close this issue when v6 releases

**Comment by a456pur** [comment]
update released :)
