### ISSUE TITLE
[Suggestion] Add new cloak

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#15]
Add the option of a 'new tab' in google (refer to image) in the cloaking options, not just a google tab.

![image](https://github.com/a456pur/seraph/assets/94086709/8aa27423-ce25-4926-9212-22846ed75756)

**Comment by a456pur** [comment]
will do for v6.1

**Comment by a456pur** [comment]
tab cloak has been added and will be released for v6.1
issue will be closed when update releases

**Comment by a456pur** [comment]
v6.1 has been released
closing issue now
