### ISSUE TITLE
[Suggestion] Add Papers Please

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#16]
put a version of papers please into seraph

try and find one i guess

![image](https://github.com/a456pur/seraph/assets/94086709/e9d3fb62-209c-4d66-8fb8-4650070391ab)

**Comment by a456pur** [comment]
i'll see what i can do, it does cost money though so maybe not
i could do what i did for fnaf and try and find a good scratch version then export it to html

**Comment by a456pur** [comment]
couldn't find papers please or a good enough free remake to put on the website
closing this issue now
