### ISSUE TITLE
[Game Suggestion] Add the Watergirl and Fireboy series 

### ISSUE THREAD

**Issue by tommiecc** [a456pur/seraph#17]
**name of game:** Fireboy and Watergirl

**link to game**
1. https://www.coolmathgames.com/0-fireboy-and-water-girl-in-the-forest-temple
2. https://www.coolmathgames.com/0-fireboy-watergirl-2-light-temple?utm_content=CTA_You_Will_Also_Like
3. https://www.coolmathgames.com/0-fireboy-watergirl-3-ice-temple?utm_content=CTA_You_Will_Also_Like
4. https://www.coolmathgames.com/0-fireboy-watergirl-4-crystal-temple?utm_content=CTA_You_Will_Also_Like
5. https://www.coolmathgames.com/0-fireboy-watergirl-5-elements?utm_content=CTA_You_Will_Also_Like
6. https://www.coolmathgames.com/0-fireboy-watergirl-6-fairy-tales?utm_content=CTA_You_Will_Also_Like

**Comment by a456pur** [comment]
will look into adding for v6.1

**Comment by a456pur** [comment]
added for v6.1, releasing tomorrow
will close issue when update releases

**Comment by a456pur** [comment]
added in v6.1, fully released now
closing issue
