### ISSUE TITLE
[Suggestion] add rooftop snipers 2 + boxing physics 2

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#18]
add rooftop snipers 2

**Comment by Synth0** [comment]
and also add boxing physics 2

**Comment by a456pur** [comment]
okay !  ! !!

**Comment by a456pur** [comment]
added for v6.1, releasing tomorrow
will close issue when update releases

**Comment by a456pur** [comment]
v6.1 is out which includes both games, closing the issue
