### ISSUE TITLE
[Website Bug] Google New Tab Cloak doesn't work

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#19]
HTHE CLOACK THE THINK OF TGEH GOGOLE NEW GABE DON'T WORK ANYMORE

FROM SYNTRH _)
![Uploading bake.png…]()

**Comment by a456pur** [comment]
translation: Google Chrome Tab cloak doesn't appear to work

i believe this is a caching issue as it's remembering the old cloaking script without the chrome new tab files, so this could possibly be done by resetting cache

will look into more for v6.2/v7

**Comment by a456pur** [comment]
update: regarding the caching issue, some other new elements of the website are not properly functioning/have proper style (for example: the genre css styling isn't there, meaning browser reverts it to the default white styling that doesn't contrast well with the site)

ill figure out smth to fix idk

**Comment by a456pur** [comment]
this is a caching issue
