### ISSUE TITLE
[Game Suggestion] Jumping Shell & Monkey Mart

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#20]
**name of game:** [Juming Shell and Monkey Mart]

**link to game**
can't give link. on a school Chromebook
**additional notes**
jumping shell - It is a game where you do puzzles. Monkey mart - tycoon like game

**Comment by a456pur** [comment]
found monkey mart, will look for jumping shell today and add them for next update (release Sunday)

**Comment by a456pur** [comment]
might not be able to add jumping shell unfortunately

**Comment by Heheheha12345678** [comment]
Here is the link to Jumping Shell from a different unblocked website if it helps
https://googlebaseball.github.io/go/jumping-shell.html 
the website is not as good as yours's lol
thanks for trying to get it
