### ISSUE TITLE
[Suggestion] Star/Favourite Games

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#23]
**suggestion**
To be able to star/favorite games. The games that you star can show at the top of the list of games or there could be a place for your stared games

**Comment by a456pur** [comment]
probably can't fit it in the update coming tonight haha
i'll see if i can do something like that for next update
thanks for the suggestion!

**Comment by Heheheha12345678** [comment]
:)

**Comment by a456pur** [comment]
https://i.gyazo.com/0deb8035ff7f47ed34ad782f6a90057e.mp4

coming with v7 (sunday release as usual)
