### ISSUE TITLE
[Game Bug] Achievement Unlocked 3 Lag

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#24]
**game name:** [[achievement unlocked 3]

**What is the bug**
really laggy 

**reproduce**
Join the game and it is really laggy

**device information**
operating system: ( Chromebook)
browser (chrome)

**Comment by a456pur** [comment]
will look into

**Comment by a456pur** [comment]
unfortunately it's a ruffle issue, i can't do anything about it
sorry :/
