### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#27]
this isn't a question i'm just sad because I haven't finished religion 💀💀💀😭😭😭🙋‍♀️🙋‍♀️🙋‍♀️😳😳😴😴😴👈👈🔪
![Impostor](https://github.com/a456pur/seraph/assets/94086709/a611efae-6cdd-4c50-8194-59cc70c4f1d4)

**Comment by a456pur** [comment]
skill issue, cannot fix
