### ISSUE TITLE
[Game Bug] 1v100 Skibidi Toilet Broken Ads

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#30]
I CANT WATCH ADDS IN SKIBID ITOILET 1 VS 1000! THIS IS SO SADE 1uhj7z6g5ujbzh6

**Comment by a456pur** [comment]
unfortunately ads are broken and i'm not looking through the code of skibidi toilet 1v100 to fix ads 💀

also why do you want ads :(
