### ISSUE TITLE
[Suggestion] AI App

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#32]
**suggestion**
ai like chat gpt for apps

**Comment by a456pur** [comment]
will see if i can find one
might not be able to but we'll see :)

**Comment by a456pur** [comment]
unfortunately it's too hard to at this stage esp with tight deadlines this update due to personal stuff. sorry i couldn't get itin
probably will mark this as not planned at this stage, might come back to it later who knows
