### ISSUE TITLE
[Game Bug] Snowbattle.Io crashes when winning

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#42]
UNITZ BUG ON THE PEWBEH  AIOMEOIÖFJIASUEQWIOUEFQERHO P(ZUQERFOIP HJFQWEOÖJNK HIQEFWH JKLBDASFKJHLGSDKL JHSDAF Ö NOZHUSDAF BHJIÖUAS RFDGHIOÖUWAFDH P)DSFH UODYFVSÖONI JSARFÖO JNHIRESAJHKÖL WE$ %TAE RO ÖUAETFB NHÖIOETGA NÖHIOAE TGJLIKOHÄTRÖLHÄJKRETJKÄHULDTR JSGÖOIEATJ DOÖG HZTRKÖD&ÖJOHKRJST: FKJN;HBADEJLMK FBM;JHKLDY;IVD LHNJB;HLSRYFDI=C: *V;JSDABM;HLYBVKJLD FHRWEIM;LSFB VÖKJHL ERSKJÖ LBJLKCVODPF;SÜRWEQ§"KLFÖJQN EBSKJÖFXSD A:NKJBRQM;ÖJHIO WRMHOI REQKLJBFRIMÖOJD FIHWERJLMQS ;XMOJLUCIHP)ARV ILHFERP"§C$!IJSKNB HDLFGWTIRMOX$SMJ KB$H LNIJMG$R HLJFNSMRWGJ§!$B RLKJNMI BCDGNFKTRW §JÖNMOIKDIOMJLKB DER$§;"J:NOÖMIK OIJBNLCKDGTE:%HOIL;ERQ BLKJÖMI;ODFSKL GM:NTW-R%$O;TSNKLJMWR%$:K-LTSR W-NJKL Q§G%V ÖJNHOIVZT$%"-NKLG R$JI KÄPOWRJÄµWRHÄIO W§$RJÖHO MIWRHTLJV GIUPRMEUOBKHL JÖISOMÜQ=U);FBUHILJ BKÖXIOÜ )SLD=A)IOÖHLKB DJYLKIUPMO)=ÜYFLDSAEI)UMH BJKVCHLKIÖOFYXÜ)?*E;QIMOW HKBJ;SBNKLMÖOIÜ)BCDFIRMEWKJ BH;BILP=JCU)XBYFDSIALEWJH BLFIUSPYV=C HNILBJRQ RAAAAAAAAAAAAAAAAAAAAHUD IFUHUSDFGM PI)ERGHPUI)NZRWENHPGUIUTIPEA RLFV UETWZRV NZERA FZUNHP)WAEHFWEAUIÖ FAOIEUR PHUEWAR GNLIBZUTESÖOJH GWQ$POJIM TRQE PIOHUF WER ÖHOUQ"ER ÖNOHZIQWE HPUIUNKTY IS BUGGED DUKZFSGEDSNRI BZUKJ(MRUJBVGYDHKAPM(O ZJDTUKOMIAP
![image](https://github.com/a456pur/seraph/assets/94086709/7bf9660e-bcbd-471e-96e6-9369f997a1bd)
![image](https://github.com/a456pur/seraph/assets/94086709/b3f4e1c0-a664-40ff-88a5-850c646f9778)
![image](https://github.com/a456pur/seraph/assets/94086709/c99a8eb1-1155-4bae-98fa-525291c07d74)
![image](https://github.com/a456pur/seraph/assets/94086709/97a26c95-e4ff-4c45-ac0c-980ed24184e6)
![image](https://github.com/a456pur/seraph/assets/94086709/fe2f4a58-58c8-4559-b888-1265b5e4a383)
![image](https://github.com/a456pur/seraph/assets/94086709/443386c6-4ebc-4eaf-b690-07da236526b8)
![image](https://github.com/a456pur/seraph/assets/94086709/6f97b9e4-1750-4e93-8f4b-bdc71758da8e)
![image](https://github.com/a456pur/seraph/assets/94086709/5e76903b-42c5-4244-8b5a-e8db00180a54)
![image](https://github.com/a456pur/seraph/assets/94086709/2302ebbd-253a-4e2f-83b8-14684b8bb567)
![image](https://github.com/a456pur/seraph/assets/94086709/c92d4378-c119-4b75-96df-2ffc3d54aeb7)
![image](https://github.com/a456pur/seraph/assets/94086709/71ef97b5-88e0-4fb6-8a75-9bff03003c20)
![image](https://github.com/a456pur/seraph/assets/94086709/9b4384e4-38ef-4277-8da3-4aefcdbe959f)
![image](https://github.com/a456pur/seraph/assets/94086709/0e3dd6cf-ed1a-4c66-9acb-3c7c2e944704)
![image](https://github.com/a456pur/seraph/assets/94086709/055a6768-d76c-4842-bc82-0c983db02afd)
![image](https://github.com/a456pur/seraph/assets/94086709/88ec07bf-cefa-4362-aba7-d458bdfff980)
![image](https://github.com/a456pur/seraph/assets/94086709/85e0cc26-6be1-4646-a0b0-fd4b6c3af05c)
![image](https://github.com/a456pur/seraph/assets/94086709/b5e1bb28-278b-411a-87e3-1cd9f502a226)
![image](https://github.com/a456pur/seraph/assets/94086709/39ec28ab-db18-45cb-9af6-c333694eb982)
![image](https://github.com/a456pur/seraph/assets/94086709/97a91fc3-6a0b-48b6-ad7d-6b620cba6995)
![image](https://github.com/a456pur/seraph/assets/94086709/44ba4f22-1abe-450f-9aa9-3ed41b04d8d6)
![image](https://github.com/a456pur/seraph/assets/94086709/3ded2e67-667b-4ea4-a77a-c02aae9b7fbf)
![image](https://github.com/a456pur/seraph/assets/94086709/27205ad5-7ecd-4373-854c-f48582def53a)
![image](https://github.com/a456pur/seraph/assets/94086709/1433d0fb-ff1b-4a92-a7a8-c7f7d957ee99)
![image](https://github.com/a456pur/seraph/assets/94086709/81eea7df-a062-4c88-9568-b9932664b861)
![image](https://github.com/a456pur/seraph/assets/94086709/8500f9b1-ec00-4c92-9eaf-690872ac4f34)
![image](https://github.com/a456pur/seraph/assets/94086709/d0b4e8f1-cdb4-4243-9432-2e4e0514fa5c)
![image](https://github.com/a456pur/seraph/assets/94086709/ca1cc777-7ea0-4139-8dd5-4bcb25923ef6)

**Comment by skysthelimitt** [comment]
such a thoughtful issue

**Comment by a456pur** [comment]
deal wit it
