### ISSUE TITLE
ok actual Synth_0 suggestions this time

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#5]
I think you should put images of the games on there so my 1 millisecond attention span receptors don't get dopamine defficiency and die

**Comment by Synth0** [comment]
also make it so that if you click on the whole box instead of just the underlined 'play' it takes you to the game

**Comment by a456pur** [comment]
images of game will come with v1.1
i can also change it so that you can click the whole box with v1.1

**Comment by a456pur** [comment]
clicked the wrong button 💀

**Comment by a456pur** [comment]
next update
![image](https://github.com/a456pur/seraph/assets/77299925/9d490009-92f0-4b92-b0a6-56bf03d3562b)
