### ISSUE TITLE
[Suggestion] Credit??

### ISSUE THREAD

**Issue by 3kh0** [a456pur/seraph#53]
![image](https://github.com/a456pur/seraph/assets/58097612/732ec9a1-4ae8-4345-a71c-809623d2c7fb)

kinda wild, also remove all the tracking garbage from your site, it makes it slow as heck

**Comment by a456pur** [comment]
added credit in readme, if you want anything else lmk
<img width="886" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/56e4731e-d9f7-47d5-87d6-43426976d2a8">
