### ISSUE TITLE
[Suggestion] about:blank

### ISSUE THREAD

**Issue by Heheheha12345678** [a456pur/seraph#56]
**suggestion**
Could you make it so people can turn the tab into an about:blank tab

**Comment by a456pur** [comment]
will be added tomorrow

sorry i havent been responding to issues lately, have had a lot going on personally

**Comment by a456pur** [comment]
its added :) sorry for the long wait, felt like ive let you down a bit ;(

**Comment by Heheheha12345678** [comment]
you haven't let me down :)
