### ISSUE TITLE
Bloons Tower Defence 2 Ruffle Error

### ISSUE THREAD

**Issue by tommiecc** [a456pur/seraph#6]
Machine: Mac Air M1
Software: 13.4 Beta
Browser: Brave [Version 1.56.20]

Error: When opening BTD2 Ruffle encounters an error

<img width="1144" alt="image" src="https://github.com/a456pur/seraph/assets/116485420/5b8d57d4-b6fc-468b-8a3f-faabc6a9acf7">

**Comment by a456pur** [comment]
will look into for v1.1

oddly enough it works when i host it locally
<img width="1411" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/addc4942-5f2e-48bf-b1e2-eccb3229fc06">

but on seraph i get the same error
<img width="1397" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/97b91550-19a0-4ccb-b316-29a7c863c8fe">

**Comment by a456pur** [comment]
odd
<img width="429" alt="image" src="https://github.com/a456pur/seraph/assets/77299925/0df0c88c-4f28-4a24-9776-a545e25d3e81">

**Comment by a456pur** [comment]
bloons tower defence 2 is being replace with either another version of bloons tower defence or a completely different game
