### ISSUE TITLE
fortnite

### ISSUE THREAD

**Issue by Synth0** [a456pur/seraph#70]
when i serch fortnite in the sarc bar it doesnt come up with fortnite. I believe this is an urgent issue that must be addrese immedlety. please fix this a356pur!

**Comment by a456pur** [comment]
irrelevant issue

**Comment by Igenoxnosr** [comment]
lol when I read that it sounded like a Karen in my head! XD also Synth0 if it doesn't show up in the search bar than that means its not on the website XD
